In [ ]:
#Mini Student Performance Analytics Notebook

In [ ]:
import pandas as pd

In [ ]:
data = {
    "student_id": [101, 102, 103, 104, 105, 106],
    "attendance_percent": [92, 67, 81, 45, 74, 88],
    "assignment_score": [18, 12, 15, 8, 14, 19],
    "quiz_score": [72, 48, 65, 30, 55, 80],
    "lab_completed": [True, False, True, False, True, True]
}
df = pd.DataFrame(data)
print(df)

   student_id  attendance_percent  assignment_score  quiz_score  lab_completed
0         101                  92                18          72           True
1         102                  67                12          48          False
2         103                  81                15          65           True
3         104                  45                 8          30          False
4         105                  74                14          55           True
5         106                  88                19          80           True

In [ ]:
df.shape

(6, 5)

In [ ]:
df.head()

   student_id  attendance_percent  assignment_score  quiz_score  lab_completed
0         101                  92                18          72           True
1         102                  67                12          48          False
2         103                  81                15          65           True
3         104                  45                 8          30          False
4         105                  74                14          55           True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          6 non-null      int64
 1   attendance_percent  6 non-null      int64
 2   assignment_score    6 non-null      int64
 3   quiz_score          6 non-null      int64
 4   lab_completed       6 non-null      bool
dtypes: bool(1), int64(4)
memory usage: 330.0 bytes

In [ ]:
df.describe()

       student_id  attendance_percent  assignment_score  quiz_score
count    6.000000            6.000000          6.000000    6.000000
mean   103.500000           74.500000         14.333333   58.333333
std      1.870829           17.073371          4.033196   18.007406
min    101.000000           45.000000          8.000000   30.000000
25%    102.250000           68.750000         12.500000   49.750000
50%    103.500000           77.500000         14.500000   60.000000
75%    104.750000           86.250000         17.250000   70.250000
max    106.000000           92.000000         19.000000   80.000000

In [ ]:
#Feature Extraction
df["total_score"] = df["assignment_score"] + df["quiz_score"]
df

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_score
0,101,92,18,72,True,90
1,102,67,12,48,False,60
2,103,81,15,65,True,80
3,104,45,8,30,False,38
4,105,74,14,55,True,69
5,106,88,19,80,True,99

In [ ]:
#Eligibility Rule for scholarship
#If Attendance>=75 and total_score>=70 and if labs are completed
df["eligible"] = ((df["attendance_percent" ]>=75) &
                 (df['total_score'] >= 70)&
                 (df['lab_completed'] == True) )
df

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_score,eligible
0,101,92,18,72,True,90,True
1,102,67,12,48,False,60,False
2,103,81,15,65,True,80,True
3,104,45,8,30,False,38,False
4,105,74,14,55,True,69,False
5,106,88,19,80,True,99,True

In [ ]:
#Filter
eligible_students = df[df["eligible"] == True]
eligible_students

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_score,eligible
0,101,92,18,72,True,90,True
2,103,81,15,65,True,80,True
5,106,88,19,80,True,99,True

In [ ]:
summary = {
    "average_attendance": df["attendance_percent"].mean(),
    "average_total_score": df["total_score"].mean(),
    "eligible_count": df["eligible"].sum(),
    "total_students": len(df)
}
summary

{'average_attendance': np.float64(74.5),
 'average_total_score': np.float64(72.66666666666667),
 'eligible_count': np.int64(3),
 'total_students': 6}

In [ ]:
#Assertions For Attendance Percentage, Assignment Score, and Quiz Score
assert df["attendance_percent"].between(0,100).all(),"Attendance percentage should be between 0 and 100"
assert df['assignment_score'].between(0,20).all(), "Assignment score should be between 0 and 20"

In [ ]:
#Semantic Error: It means, syntactically correct but semantically wrong. Yaha par assignment aur attendance ko ek saath add to kr de rhe hain, numbers hain, but unka koi matlab nahi reh jaata, nirarthak hain.
#df["w_total"] = df["assignment_score"] + df["attendance_percent"]

df[["student_id","assignment_score","quiz_score","attendance_percent",]]

   student_id  assignment_score  quiz_score  attendance_percent
0         101                18          72                  92
1         102                12          48                  67
2         103                15          65                  81
3         104                 8          30                  45
4         105                14          55                  74
5         106                19          80                  88

In [ ]:
#Libraries
#Data = pandas
#numbers = numpy
#Visualizations = matplotlib, seaborn
#AI/ML training = pytorch, TensorFlow, scikit

In [ ]:
def prepare_record(student):
    students = student.copy()
    students["name"] = students["name"].strip().title()
    students["average"] = sum(students["marks"]) / len(students["marks"])
    return students

raw = {"name": "  riya ", "marks": [55, 63, 71]}
prepared = prepare_record(raw)

print(raw)
print(prepared)
#rewrite the prepare_record so that raw remains unchanged.
#use dictionary unpacking to contruct a new record

{'name': '  riya ', 'marks': [55, 63, 71]}
{'name': 'Riya', 'marks': [55, 63, 71], 'average': 63.0}